# Generated by Django 5.1.5 on 2025-02-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponsapp', '0003_remove_coupon_max_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
