# Generated by Django 5.1.5 on 2025-02-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponsapp', '0004_coupon_max_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
