# Generated by Django 5.1.5 on 2025-01-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_size_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
