# Generated by Django 5.1.5 on 2025-02-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
