# Generated by Django 5.1.5 on 2025-02-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
