# Generated by Django 5.1.5 on 2025-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
