# Generated by Django 5.1.5 on 2025-02-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_referral_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
