# Generated by Django 5.1.5 on 2025-01-30 11:28

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
