# Generated by Django 5.1.5 on 2025-02-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='order_placed', max_length=20),
        ),
    ]
