# Generated by Django 5.1.5 on 2025-02-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
