# Generated by Django 5.1.5 on 2025-02-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
