# Generated by Django 5.1.5 on 2025-02-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponsapp', '0001_initial'),
        ('orders', '0021_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='couponsapp.coupon'),
        ),
    ]
