# Generated by Django 5.1.5 on 2025-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_order_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
