# Generated by Django 5.1.5 on 2025-02-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
