# Generated by Django 5.1.5 on 2025-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retry_payment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
